[build]
  command = "pnpm run build || ( npm run install pnpm && pnpm run build )"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=2592000"